
services:
  web:
    build: .
    volumes:
      - /home/easharp/.docker
    environment: 
      DATABASE_URL: "postgresql+asyncpg://summago:pwdsumm@db:5432/summ_db"
      REDIS_URL: "redis://redis/0"
    ports:
      - "8001:8001"

    depends_on:
      - db
      - redis

    networks:
      - app-network

  db:
    image: postgres:17

    environment:
      POSTGRES_USER: summago
      POSTGRES_DB: summ_db
      POSTGRES_PASSWORD: pwdsumm
    ports:
     - "5432:5432"

    volumes:
      - db-data:/var/lib/postgresql/data

    networks:
      - app-network
  redis:
    image: redis:latest

    networks:
     - app-network

  celery:
    build: .

    command: celery -A src.services.celery.c_app worker --loglevel=INFO

    volumes:
      - /home/easharp/.docker

    depends_on:
      - redis

    environment:
      REDIS_URL: "redis://redis/0"

    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge