"""Changed user_id type

Revision ID: 68d6c0089eaf
Revises: bb2b2be78af4
Create Date: 2024-11-03 20:37:40.171337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68d6c0089eaf'
down_revision: Union[str, None] = 'bb2b2be78af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcribe')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcribe',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('task_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('result', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'user_id', name='transcribe_pkey')
    )
    # ### end Alembic commands ###
